# Isaac Lab G1 Robot Body Names Configuration
# This file defines the body order used in Isaac Lab simulation for the G1 robot
# Total: 30 bodies (confirmed by debug_body_indices.py)

isaac_body_names:
  - "pelvis"                    # 0
  - "left_hip_pitch_link"       # 1
  - "right_hip_pitch_link"      # 2
  - "waist_yaw_link"            # 3
  - "left_hip_roll_link"        # 4
  - "right_hip_roll_link"       # 5
  - "waist_roll_link"           # 6
  - "left_hip_yaw_link"         # 7
  - "right_hip_yaw_link"        # 8
  - "torso_link"                # 9 ← NPZ 파일의 anchor body
  - "left_knee_link"            # 10
  - "right_knee_link"           # 11
  - "left_shoulder_pitch_link"  # 12
  - "right_shoulder_pitch_link" # 13
  - "left_ankle_pitch_link"     # 14
  - "right_ankle_pitch_link"    # 15
  - "left_shoulder_roll_link"   # 16
  - "right_shoulder_roll_link"  # 17
  - "left_ankle_roll_link"      # 18
  - "right_ankle_roll_link"     # 19
  - "left_shoulder_yaw_link"    # 20
  - "right_shoulder_yaw_link"   # 21
  - "left_elbow_link"           # 22
  - "right_elbow_link"          # 23
  - "left_wrist_roll_link"      # 24
  - "right_wrist_roll_link"     # 25
  - "left_wrist_pitch_link"     # 26
  - "right_wrist_pitch_link"    # 27
  - "left_wrist_yaw_link"       # 28
  - "right_wrist_yaw_link"      # 29

# Body mapping information
body_mapping:
  description: "Isaac Lab body order for G1 robot"
  total_bodies: 30
  anchor_body:
    name: "torso_link"
    index: 9
    description: "Main anchor body for tracking"
  body_groups:
    pelvis:
      - "pelvis"
    left_leg:
      - "left_hip_pitch_link"
      - "left_hip_roll_link"
      - "left_hip_yaw_link"
      - "left_knee_link"
      - "left_ankle_pitch_link"
      - "left_ankle_roll_link"
    right_leg:
      - "right_hip_pitch_link"
      - "right_hip_roll_link"
      - "right_hip_yaw_link"
      - "right_knee_link"
      - "right_ankle_pitch_link"
      - "right_ankle_roll_link"
    waist:
      - "waist_yaw_link"
      - "waist_roll_link"
    torso:
      - "torso_link"
    left_arm:
      - "left_shoulder_pitch_link"
      - "left_shoulder_roll_link"
      - "left_shoulder_yaw_link"
      - "left_elbow_link"
      - "left_wrist_roll_link"
      - "left_wrist_pitch_link"
      - "left_wrist_yaw_link"
    right_arm:
      - "right_shoulder_pitch_link"
      - "right_shoulder_roll_link"
      - "right_shoulder_yaw_link"
      - "right_elbow_link"
      - "right_wrist_roll_link"
      - "right_wrist_pitch_link"
      - "right_wrist_yaw_link"
